// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiGalleryByGalleryIdData, DeleteApiGalleryByGalleryIdHardData, DeleteApiGalleryByGalleryIdHardResponses, DeleteApiGalleryByGalleryIdResponses, DeleteApiGalleryMediaByMediaIdData, DeleteApiGalleryMediaByMediaIdHardData, DeleteApiGalleryMediaByMediaIdHardResponses, DeleteApiGalleryMediaByMediaIdResponses, GetApiGalleryByGalleryIdData, GetApiGalleryByGalleryIdResponses, GetApiGalleryData, GetApiGalleryResponses, GetApiGuestsRequestsData, GetApiGuestsRequestsResponses, PatchApiGuestsRequestsByUserIdData, PatchApiGuestsRequestsByUserIdResponses, PostApiAuthTelegramData, PostApiAuthTelegramResponses, PostApiGuestsRequestData, PostApiGuestsRequestResponses, PostApiWebhookData, PostApiWebhookResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate via Telegram initData
 */
export const postApiAuthTelegram = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthTelegramData, ThrowOnError>) => (options.client ?? client).post<PostApiAuthTelegramResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/telegram',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all guest galleries with previews
 */
export const getApiGallery = <ThrowOnError extends boolean = false>(options?: Options<GetApiGalleryData, ThrowOnError>) => (options?.client ?? client).get<GetApiGalleryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/',
    ...options
});

/**
 * Soft delete a gallery (owner only)
 */
export const deleteApiGalleryByGalleryId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGalleryByGalleryIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGalleryByGalleryIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/{galleryId}',
    ...options
});

/**
 * Get a specific guest gallery with all photos
 */
export const getApiGalleryByGalleryId = <ThrowOnError extends boolean = false>(options: Options<GetApiGalleryByGalleryIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGalleryByGalleryIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/{galleryId}',
    ...options
});

/**
 * Soft delete a photo (owner only)
 */
export const deleteApiGalleryMediaByMediaId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGalleryMediaByMediaIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGalleryMediaByMediaIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/media/{mediaId}',
    ...options
});

/**
 * Hard delete a photo (admin only)
 */
export const deleteApiGalleryMediaByMediaIdHard = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGalleryMediaByMediaIdHardData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGalleryMediaByMediaIdHardResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/media/{mediaId}/hard',
    ...options
});

/**
 * Hard delete a gallery (admin only)
 */
export const deleteApiGalleryByGalleryIdHard = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGalleryByGalleryIdHardData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGalleryByGalleryIdHardResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/{galleryId}/hard',
    ...options
});

/**
 * Submit request to become a guest
 */
export const postApiGuestsRequest = <ThrowOnError extends boolean = false>(options?: Options<PostApiGuestsRequestData, ThrowOnError>) => (options?.client ?? client).post<PostApiGuestsRequestResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/request',
    ...options
});

/**
 * List all guest requests (admin only)
 */
export const getApiGuestsRequests = <ThrowOnError extends boolean = false>(options?: Options<GetApiGuestsRequestsData, ThrowOnError>) => (options?.client ?? client).get<GetApiGuestsRequestsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/requests',
    ...options
});

/**
 * Approve or deny a guest request (admin only)
 */
export const patchApiGuestsRequestsByUserId = <ThrowOnError extends boolean = false>(options: Options<PatchApiGuestsRequestsByUserIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiGuestsRequestsByUserIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/requests/{userId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiWebhook = <ThrowOnError extends boolean = false>(options?: Options<PostApiWebhookData, ThrowOnError>) => (options?.client ?? client).post<PostApiWebhookResponses, unknown, ThrowOnError>({ url: '/api/webhook/', ...options });
