// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiGalleryMediaByMediaIdData, DeleteApiGalleryMediaByMediaIdResponses, GetApiGalleryByGalleryIdData, GetApiGalleryByGalleryIdResponses, GetApiGalleryData, GetApiGalleryResponses, GetApiGuestsRequestMeData, GetApiGuestsRequestMeResponses, GetApiGuestsRequestsData, GetApiGuestsRequestsResponses, GetApiRsvpAllData, GetApiRsvpAllResponses, GetApiRsvpMeData, GetApiRsvpMeResponses, GetApiRsvpStatsData, GetApiRsvpStatsResponses, PatchApiGuestsRequestsByRequestIdData, PatchApiGuestsRequestsByRequestIdResponses, PostApiAuthTelegramData, PostApiAuthTelegramResponses, PostApiGalleryUploadData, PostApiGalleryUploadResponses, PostApiGuestsRequestData, PostApiGuestsRequestResponses, PostApiRsvpData, PostApiRsvpResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate via Telegram initData
 */
export const postApiAuthTelegram = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthTelegramData, ThrowOnError>) => (options.client ?? client).post<PostApiAuthTelegramResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/auth/telegram',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Submit or update RSVP
 */
export const postApiRsvp = <ThrowOnError extends boolean = false>(options: Options<PostApiRsvpData, ThrowOnError>) => (options.client ?? client).post<PostApiRsvpResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rsvp/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get own RSVP
 */
export const getApiRsvpMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiRsvpMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiRsvpMeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rsvp/me',
    ...options
});

/**
 * Get all RSVPs (admin only)
 */
export const getApiRsvpAll = <ThrowOnError extends boolean = false>(options?: Options<GetApiRsvpAllData, ThrowOnError>) => (options?.client ?? client).get<GetApiRsvpAllResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rsvp/all',
    ...options
});

/**
 * Get attendance stats (admin only)
 */
export const getApiRsvpStats = <ThrowOnError extends boolean = false>(options?: Options<GetApiRsvpStatsData, ThrowOnError>) => (options?.client ?? client).get<GetApiRsvpStatsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/rsvp/stats',
    ...options
});

/**
 * Upload a photo (confirmed guests only)
 */
export const postApiGalleryUpload = <ThrowOnError extends boolean = false>(options?: Options<PostApiGalleryUploadData, ThrowOnError>) => (options?.client ?? client).post<PostApiGalleryUploadResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/upload',
    ...options
});

/**
 * List all guest galleries with previews
 */
export const getApiGallery = <ThrowOnError extends boolean = false>(options?: Options<GetApiGalleryData, ThrowOnError>) => (options?.client ?? client).get<GetApiGalleryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/',
    ...options
});

/**
 * Get a specific guest gallery with all photos
 */
export const getApiGalleryByGalleryId = <ThrowOnError extends boolean = false>(options: Options<GetApiGalleryByGalleryIdData, ThrowOnError>) => (options.client ?? client).get<GetApiGalleryByGalleryIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/{galleryId}',
    ...options
});

/**
 * Delete a photo (admin or owner)
 */
export const deleteApiGalleryMediaByMediaId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiGalleryMediaByMediaIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiGalleryMediaByMediaIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/gallery/media/{mediaId}',
    ...options
});

/**
 * Submit request to become a guest
 */
export const postApiGuestsRequest = <ThrowOnError extends boolean = false>(options?: Options<PostApiGuestsRequestData, ThrowOnError>) => (options?.client ?? client).post<PostApiGuestsRequestResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/request',
    ...options
});

/**
 * Check own request status
 */
export const getApiGuestsRequestMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiGuestsRequestMeData, ThrowOnError>) => (options?.client ?? client).get<GetApiGuestsRequestMeResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/request/me',
    ...options
});

/**
 * List all guest requests (admin only)
 */
export const getApiGuestsRequests = <ThrowOnError extends boolean = false>(options?: Options<GetApiGuestsRequestsData, ThrowOnError>) => (options?.client ?? client).get<GetApiGuestsRequestsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/requests',
    ...options
});

/**
 * Approve or deny a guest request (admin only)
 */
export const patchApiGuestsRequestsByRequestId = <ThrowOnError extends boolean = false>(options: Options<PatchApiGuestsRequestsByRequestIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiGuestsRequestsByRequestIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/guests/requests/{requestId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
