// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://yz-wedding.vn.ua' | 'http://localhost:4000' | (string & {});
};

export type PostApiAuthTelegramData = {
    body: {
        initData: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/telegram';
};

export type PostApiAuthTelegramResponses = {
    /**
     * Default Response
     */
    200: {
        user: {
            firstName: string;
            lastName?: string;
            role: 'admin' | 'guest';
            approvalStatus?: 'pending' | 'approved' | 'denied';
        };
    };
};

export type PostApiAuthTelegramResponse = PostApiAuthTelegramResponses[keyof PostApiAuthTelegramResponses];

export type PostApiGalleryUploadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gallery/upload';
};

export type PostApiGalleryUploadResponses = {
    /**
     * Default Response
     */
    201: {
        url: string;
        thumbnailUrl: string;
    };
};

export type PostApiGalleryUploadResponse = PostApiGalleryUploadResponses[keyof PostApiGalleryUploadResponses];

export type GetApiGalleryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gallery/';
};

export type GetApiGalleryResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        guestName: string;
        coverPhotoUrl?: string;
        photoCount: number;
        previews: Array<string>;
    }>;
};

export type GetApiGalleryResponse = GetApiGalleryResponses[keyof GetApiGalleryResponses];

export type GetApiGalleryByGalleryIdData = {
    body?: never;
    path: {
        galleryId: string;
    };
    query?: never;
    url: '/api/gallery/{galleryId}';
};

export type GetApiGalleryByGalleryIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        guestName: string;
        photoCount: number;
        photos: Array<{
            id: string;
            url: string;
            thumbnailUrl: string;
            uploadedAt: string;
        }>;
    };
};

export type GetApiGalleryByGalleryIdResponse = GetApiGalleryByGalleryIdResponses[keyof GetApiGalleryByGalleryIdResponses];

export type DeleteApiGalleryMediaByMediaIdData = {
    body?: never;
    path: {
        mediaId: string;
    };
    query?: never;
    url: '/api/gallery/media/{mediaId}';
};

export type DeleteApiGalleryMediaByMediaIdResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type DeleteApiGalleryMediaByMediaIdResponse = DeleteApiGalleryMediaByMediaIdResponses[keyof DeleteApiGalleryMediaByMediaIdResponses];

export type PostApiGuestsRequestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guests/request';
};

export type PostApiGuestsRequestResponses = {
    /**
     * Default Response
     */
    201: {
        message: string;
    };
};

export type PostApiGuestsRequestResponse = PostApiGuestsRequestResponses[keyof PostApiGuestsRequestResponses];

export type GetApiGuestsRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guests/requests';
};

export type GetApiGuestsRequestsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        firstName?: string;
        lastName?: string;
        username?: string;
        approvalStatus: 'pending' | 'approved' | 'denied';
        createdAt: string;
    }>;
};

export type GetApiGuestsRequestsResponse = GetApiGuestsRequestsResponses[keyof GetApiGuestsRequestsResponses];

export type PatchApiGuestsRequestsByUserIdData = {
    body: {
        action: 'approve' | 'deny';
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/guests/requests/{userId}';
};

export type PatchApiGuestsRequestsByUserIdResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type PatchApiGuestsRequestsByUserIdResponse = PatchApiGuestsRequestsByUserIdResponses[keyof PatchApiGuestsRequestsByUserIdResponses];
