// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://yz-wedding.vn.ua' | 'http://localhost:4000' | (string & {});
};

export type PostApiAuthTelegramData = {
    body: {
        initData: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/telegram';
};

export type PostApiAuthTelegramResponses = {
    /**
     * Default Response
     */
    200: {
        token: string;
        user: {
            firstName: string;
            lastName?: string;
            role: 'admin' | 'guest';
        };
    };
};

export type PostApiAuthTelegramResponse = PostApiAuthTelegramResponses[keyof PostApiAuthTelegramResponses];

export type PostApiRsvpData = {
    body: {
        status: 'attending' | 'not_attending' | 'maybe';
    };
    path?: never;
    query?: never;
    url: '/api/rsvp/';
};

export type PostApiRsvpResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type PostApiRsvpResponse = PostApiRsvpResponses[keyof PostApiRsvpResponses];

export type GetApiRsvpMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rsvp/me';
};

export type GetApiRsvpMeResponses = {
    /**
     * Default Response
     */
    200: {
        userId: string;
        status: string;
        createdAt: string;
        updatedAt?: string;
    };
};

export type GetApiRsvpMeResponse = GetApiRsvpMeResponses[keyof GetApiRsvpMeResponses];

export type GetApiRsvpAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rsvp/all';
};

export type GetApiRsvpAllResponses = {
    /**
     * Default Response
     */
    200: Array<{
        userId: string;
        status: string;
        guest: string;
    }>;
};

export type GetApiRsvpAllResponse = GetApiRsvpAllResponses[keyof GetApiRsvpAllResponses];

export type GetApiRsvpStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rsvp/stats';
};

export type GetApiRsvpStatsResponses = {
    /**
     * Default Response
     */
    200: {
        attending: number;
        notAttending: number;
        maybe: number;
    };
};

export type GetApiRsvpStatsResponse = GetApiRsvpStatsResponses[keyof GetApiRsvpStatsResponses];

export type PostApiGalleryUploadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gallery/upload';
};

export type PostApiGalleryUploadResponses = {
    /**
     * Default Response
     */
    201: {
        url: string;
        thumbnailUrl: string;
    };
};

export type PostApiGalleryUploadResponse = PostApiGalleryUploadResponses[keyof PostApiGalleryUploadResponses];

export type GetApiGalleryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/gallery/';
};

export type GetApiGalleryResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        guestName: string;
        coverPhotoUrl?: string;
        photoCount: number;
        previews: Array<string>;
    }>;
};

export type GetApiGalleryResponse = GetApiGalleryResponses[keyof GetApiGalleryResponses];

export type GetApiGalleryByGalleryIdData = {
    body?: never;
    path: {
        galleryId: string;
    };
    query?: never;
    url: '/api/gallery/{galleryId}';
};

export type GetApiGalleryByGalleryIdResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        guestName: string;
        photoCount: number;
        photos: Array<{
            id: string;
            url: string;
            thumbnailUrl: string;
            uploadedAt: string;
        }>;
    };
};

export type GetApiGalleryByGalleryIdResponse = GetApiGalleryByGalleryIdResponses[keyof GetApiGalleryByGalleryIdResponses];

export type DeleteApiGalleryMediaByMediaIdData = {
    body?: never;
    path: {
        mediaId: string;
    };
    query?: never;
    url: '/api/gallery/media/{mediaId}';
};

export type DeleteApiGalleryMediaByMediaIdResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type DeleteApiGalleryMediaByMediaIdResponse = DeleteApiGalleryMediaByMediaIdResponses[keyof DeleteApiGalleryMediaByMediaIdResponses];

export type PostApiGuestsRequestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guests/request';
};

export type PostApiGuestsRequestResponses = {
    /**
     * Default Response
     */
    201: {
        message: string;
    };
};

export type PostApiGuestsRequestResponse = PostApiGuestsRequestResponses[keyof PostApiGuestsRequestResponses];

export type GetApiGuestsRequestMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guests/request/me';
};

export type GetApiGuestsRequestMeResponses = {
    /**
     * Default Response
     */
    200: {
        status: 'pending' | 'approved' | 'denied';
    };
};

export type GetApiGuestsRequestMeResponse = GetApiGuestsRequestMeResponses[keyof GetApiGuestsRequestMeResponses];

export type GetApiGuestsRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/guests/requests';
};

export type GetApiGuestsRequestsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        userId: string;
        status: string;
        createdAt: string;
        user?: {
            firstName?: string;
            lastName?: string;
            username?: string;
        };
    }>;
};

export type GetApiGuestsRequestsResponse = GetApiGuestsRequestsResponses[keyof GetApiGuestsRequestsResponses];

export type PatchApiGuestsRequestsByRequestIdData = {
    body: {
        action: 'approve' | 'deny';
    };
    path: {
        requestId: string;
    };
    query?: never;
    url: '/api/guests/requests/{requestId}';
};

export type PatchApiGuestsRequestsByRequestIdResponses = {
    /**
     * Default Response
     */
    200: {
        message: string;
    };
};

export type PatchApiGuestsRequestsByRequestIdResponse = PatchApiGuestsRequestsByRequestIdResponses[keyof PatchApiGuestsRequestsByRequestIdResponses];
